### ISSUE TITLE
Use reproducible file paths

### ISSUE THREAD

**Issue by JackEdTaylor** [mello-y/MSc5_research_project#3]
At the moment, files are referenced with absolute paths in raw text. File paths are more reproducible when they **(1)** specify *relative* locations (relative to the relevant script's location/working directory), and **(2)** are platform-independent.

### 1. Use relative file paths instead of absolute file paths

As an example, this code requires that the person running your code has the file `DTI_demographics_Dublin.xls` saved in a specific location, in `/Users/mello/data/MSc5_research_project/data/`:

```python
demographic_DWI = pd.read_excel(r'/Users/mello/data/MSc5_research_project/data/DTI_demographics_Dublin.xls')
```

This will only work if the person running your code has the data saved in that specific location, which is very unlikely. As it stands they will have to put some work in to reproduce this step. Instead, use a *relative* path, to reference files in the repository, such as:

```python
demographic_DWI = pd.read_excel(r'../data/DTI_demographics_Dublin.xls')
```

Here, `..` indicates that the `data` directory is up one level in the directory tree. This makes sense if the code is being run in a script in the `code` folder, as people will usually expect the required working directory to be the location of the script they are running.

It's also important to make sure that the repository contains the relevant data. If the data is too large, you should still not use an absolute path. One option might be to provide code that users can run to automatically download the required files to the `data` directory.

### 2. Use platform-independent file paths

Different operating systems often use different characters to separate file paths. For instance, Windows will accept a backslash `\`, whereas linux will not. A good rule of thumb for reproducibility is to specify file paths in a way that is more platform-independent. `os.path.join()` is quite good for this, and `os.pardir()` can be used as a platform-independent alternative to `'..'`. For example:

```python
import pandas as pd
import os

demographic_DWI_path = os.path.join(os.pardir(), 'data', 'DTI_demographics_Dublin.xls')
demographic_DWI = pd.read_excel(demographic_DWI_path)
```

**Comment by JackEdTaylor** [comment]
I just noticed that you have some example code in a cell to download data in [code/Data_exploration.ipynb](https://github.com/mello-y/MSc5_research_project/blob/update/code/Data_exploration.ipynb), `3.1.1 Download the .mat files`, which shows how you can download the MATLAB data - cool! 😎

You could just replace the absolute file paths with relative file paths (e.g., saving in `../data`) to make that more reproducible.

**Comment by mello-y** [comment]
Thank you very much for the comments. I adjusted the file paths and used relative and platform-independent file paths!
